// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XC_71e9P-0AmuOtcZSb-8cgMYnjZ19Y',
    appId: '1:328683608533:web:d4b939b9731e269b2b455c',
    messagingSenderId: '328683608533',
    projectId: 'javacode-879b5',
    authDomain: 'javacode-879b5.firebaseapp.com',
    storageBucket: 'javacode-879b5.appspot.com',
    measurementId: 'G-MJ0CY2KPBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6EVTI_wGYtoEugElAHGT6sLd5PixWFAI',
    appId: '1:328683608533:android:4fa507dbaae5d4142b455c',
    messagingSenderId: '328683608533',
    projectId: 'javacode-879b5',
    storageBucket: 'javacode-879b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvYfPOkvzpYO_m5ajhr0xp7tNDvyQ-67Y',
    appId: '1:328683608533:ios:58e639eb7adcf3662b455c',
    messagingSenderId: '328683608533',
    projectId: 'javacode-879b5',
    storageBucket: 'javacode-879b5.appspot.com',
    iosClientId: '328683608533-4jkqafhme6bu51u0fvrk5o4kogn94l22.apps.googleusercontent.com',
    iosBundleId: 'com.example.javacode',
  );
}
